### ISSUE TITLE
Spring Cloud refresh causes CloudSqlEnvironmentPostProcessor to throw IllegalStateException

### ISSUE THREAD

**Issue by stefanscheidt** [GoogleCloudPlatform/spring-cloud-gcp#982] opened 2022-03-07 16:41 UTC
When exposing the actuator endpoint `refresh` provided by Spring Cloud, calling this endpoint will lead to a re-execution of `CloudSqlEnvironmentPostProcessor:: postProcessEnvironment`. At the end of this method, the static method `CoreSocketFactory::setApplicationName` will be called. In this state, the `coreSocketFactory` singleton inside of `CoreSocketFactory` will not be null, thus `CoreSocketFactory::setApplicationName` will throw an `IllegalStateException("Unable to set ApplicationName - SQLAdmin client already initialized.")`.

Stacktrace:

```
java.lang.IllegalStateException: Unable to set ApplicationName - SQLAdmin client already initialized.
	at com.google.cloud.sql.core.CoreSocketFactory.setApplicationName(CoreSocketFactory.java:449)
	at com.google.cloud.spring.autoconfigure.sql.CloudSqlEnvironmentPostProcessor.postProcessEnvironment(CloudSqlEnvironmentPostProcessor.java:92)
	at org.springframework.cloud.context.refresh.ConfigDataContextRefresher.updateEnvironment(ConfigDataContextRefresher.java:92)
	at org.springframework.cloud.context.refresh.ContextRefresher.refreshEnvironment(ContextRefresher.java:101)
	at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:94)
	at org.springframework.cloud.endpoint.RefreshEndpoint.refresh(RefreshEndpoint.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:74)
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60)
	at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$ServletWebOperationAdapter.handle(AbstractWebMvcEndpointHandlerMapping.java:336)
	at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(AbstractWebMvcEndpointHandlerMapping.java:421)
	at jdk.internal.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.boot.actuate.autoconfigure.web.servlet.CompositeHandlerAdapter.handle(CompositeHandlerAdapter.java:58)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:204)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Library versions used:

Spring Boot 2.6.3, Spring Cloud 3.1.1, Spring Cloud GCP 3.1.0

**Comment by mpeddada1** [comment] 2022-03-07 21:51
Thank you for bringing this to our attention @stefanscheidt! would you be able to provide a small reproducer sample so that we can explore this further?

**Comment by stefanscheidt** [comment] 2022-03-08 14:45
Hi - Thanks for the quick reply!

I can build a simple [Spring Initializr](https://start.spring.io/) based Spring Boot service with the necessary dependencies and configuration that would cause the problem when deployed to an actual environment with CloudSQL access. Only in this case (see <https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessor.java#L48>) the critical code is executed.

Would that help?

**Comment by mpeddada1** [comment] 2022-03-08 22:42
Yes, that would be helpful. Any reproducible example that results in the same error would be great. Feel free to share the configurations you are setting (if they don't contain any sensitive info) as well.

**Comment by stefanscheidt** [comment] 2022-03-09 08:11
OK. I was just now able to reproduce the problem with our Spring Boot service running locally using `gcloud auth application-default login`. I will try to strip down this service to the bare minimum and push it with a README to a public GitHub repo - but probably not before beginning of next week.

**Comment by mpeddada1** [comment] 2022-03-10 20:20
Awesome, looking forward to it.

**Comment by stefanscheidt** [comment] 2022-03-11 17:50
You can find the sample application to reproduce the issue [here](https://github.com/stefanscheidt/cloud-sql-sample).
Please let me know if you need further assistance reproducing the issue.

**Comment by meltsufin** [comment] 2022-03-14 20:39
@stefanscheidt Thanks for the reproducer and detailed instructions on how to run. We can work around this failure as in #1002. However, it won't actually refresh credentials and such because `CoreSocketFactory.getInstance()` creates a singleton without any way to reset it. We need to add the reset capability to the `jdbc-socket-factory-core`.

**Comment by stefanscheidt** [comment] 2022-03-14 21:24
Hi @meltsufin thanks for the suggested fix. But actually the use case we had in mind was exactly a refresh after a change of the credentials of the service account that is used to establish the connection to the Cloud SQL database. Thus #1002 alone wouldn't help us, we would need https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/776 too. I will track this issue.

**Comment by elefeint** [comment] 2022-03-21 15:17
@stefanscheidt Thanks for confirming!

**Comment by zhumin8** [comment] 2022-08-04 19:51
Since issue lies in `jdbc-socket-factory-core` not this repo, closing this as part of cleanup. Please re-open if it's still relevant.

**Closed by zhumin8** 2022-08-04 19:51 UTC
Labels: p2, cloud-sql
