### ISSUE TITLE
Entity returned by FirestoreTemplate.save has id == null if id is auto generated

### ISSUE THREAD

**Issue by Pojahn-Fortum** [GoogleCloudPlatform/spring-cloud-gcp#231] opened 2021-01-27 21:38 UTC
When saving an entity, you may choose to not to set the ID to let Firestore generate it for you. Similar functionality exists in nearly all databases.

So if you create a new user:

```java
User usr = new User(null, "first_name", "last_name); 
User returnedUsr = firestoreTemplate.save(user).block(); 
```

If we try to print `returnedUsr.getId()`, we will see that it's null. The only way to currently get the ID is to either do a findAll() or query by some other property. 

Looking at the source code of FirestoreTemplate.saveAll, I can see that the ID is present and there is no need to do an extra request to fetch it. Would be very convenient if the returned entity have its `DocumentId` set.

**Comment by meltsufin** [comment] 2021-01-28 02:00
@Pojahn-Fortum This makes sense. Would you want the same `usr` object returned, or a new object created? Currently the same object is returned, which is more efficient. As always, you are welcome to create a PR for this. Thanks!

**Comment by PojahnM** [comment] 2021-01-28 13:01
Yes it's efficient but have very little to no use. In a real life application, we would likely never be able to find out which entity we just created because of the absents of the id. 

Returning the same object with the id field populated could be tricky. It may be immutable or something?

Maybe run the `Document` through the registered class mapper? I think that's most consistent.

I have sadly little time to contribute.

**Comment by meltsufin** [comment] 2021-01-28 20:02
No problem, we'll try to get to it or maybe someone else will pick it up.

**Comment by abhijeetshuklaoist** [comment] 2021-01-30 19:20
@meltsufin Hey, I would like to work on this. But I am new to community so might need little help.

**Comment by meltsufin** [comment] 2021-02-01 14:59
Hi @abhijeetshuklaoist, thanks for you interest in helping out. We would love to help you get started. Just let us know what you need. One way to start would be to open a draft PR, and we can guide you on it.

**Comment by abhijeetshuklaoist** [comment] 2021-02-05 16:01
Thanks a lot @meltsufin 
I have started working on this. I tried to reproduce the issue using test where I removed the id and then made a call to saveAll and in response I could see the id. 
Any idea what I am doing wrong or any hint would be really helpful as I have started OpenSource contribution just a few weeks back. 
Thanks
@Pojahn-Fortum Could you please help me reproduce the issue.  

[0] https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/258/files

**Comment by PojahnM** [comment] 2021-02-05 16:12
Here is my test:

```kotlin
	@Test
	fun `returned entity is populated with id`() {
		val playerEntity = TestData.playerEntity() //Set all fields to random value expect id
		expectThat(playerEntity.id).isNull()
		
		val fetchedEntity = playerRepository.saveAll(listOf(playerEntity))
			.collectList()
			.block()!!
			.first()
		
		expectThat(fetchedEntity.id).isNotNull() //Failure! id is null
	}
```

I am using `com.google.cloud:spring-cloud-gcp-dependencies:2.0.0` and `org.springframework.cloud:spring-cloud-dependencies:2020.0.0`. It's also worth noting that I am using a Firestore emulator.

**Comment by emmileaf** [comment] 2022-07-29 20:25
Thank you @bijukunjummen for the contribution! We will review your PR for adding this check to the tests and addressing this issue.

I tried to reproduce this problem in both Java and Kotlin with Firestore emulator, but am also seeing the generated ID returned as expected, in line with earlier commenters.

**Comment by emmileaf** [comment] 2022-08-02 17:58
Closing as expected behavior is observed and validated.

**Closed by emmileaf** 2022-08-02 17:58 UTC
Labels: enhancement, good first issue, P3, firestore
