### ISSUE TITLE
More than one TaskScheduler when using pub/sub and scheduling together

### ISSUE THREAD

**Issue by alexandreBaronZnk** [GoogleCloudPlatform/spring-cloud-gcp#2454] opened 2023-12-13 14:25 UTC
With the following dependencies :
* `spring-boot 3.2.0`
* `spring-cloud-gcp 4.9.0`

When using the dependency `spring-cloud-gcp-starter-pubsub` and activate the scheduling with this Spring annotation `@EnableScheduling`, the following log is displayed in the console :

```
2023-12-13T15:08:54.997+01:00  INFO 25360 --- [my-app] [           main] [                                                 ] o.s.s.config.TaskSchedulerRouter         : More than one TaskScheduler bean exists within the context, and none is named 'taskScheduler'. Mark one of them as primary or name it 'taskScheduler' (possibly as an alias); or implement the SchedulingConfigurer interface and call ScheduledTaskRegistrar#setScheduler explicitly within the configureTasks() callback: [pubsubPublisherThreadPool, globalPubSubSubscriberThreadPoolScheduler]
```

With the debug activated on Spring Boot startup, the following explaination is displayed.

```
   TaskSchedulingConfigurations.TaskSchedulerConfiguration:
      Did not match:
         - @ConditionalOnMissingBean (types: org.springframework.scheduling.TaskScheduler,java.util.concurrent.ScheduledExecutorService; SearchStrategy: all) found beans of type 'org.springframework.scheduling.TaskScheduler' pubsubPublisherThreadPool (OnBeanCondition)
```

IMHO, a bean named `taskScheduler` must be created even if `spring-cloud-gcp-starter-pubsub` is present.
And thread pools for scheduling and pub/sub interactions should be distincts.
Perhaps, just add the annotation `@AutoConfigureAfter(TaskSchedulingAutoConfiguration.class)` to the `GcpPubSubAutoConfiguration` should be enough to have all thread pools created.

**Comment by mpeddada1** [comment] 2023-12-15 20:22
@alexandreBaronZnk Thanks for creating this issue! Do you happen to have a reproducer that we can try out to observe this behavior?

**Comment by meltsufin** [comment] 2024-04-10 22:10
@alexandreBaronZnk Have you tried creating your own bean called `taskScheduler`? It seems to work with your sample project.

```java
	@Bean
	public TaskScheduler taskScheduler() {
		ThreadPoolTaskScheduler scheduler = new ThreadPoolTaskScheduler();
		scheduler.setPoolSize(1);
		scheduler.setThreadNamePrefix("cron");
		scheduler.setDaemon(true);
		return scheduler;
	}
```

**Comment by meltsufin** [comment] 2024-04-12 15:46
Closing for now, but please re-open, if you think a change should be made in Spring Cloud GCP.

**Closed by meltsufin** 2024-04-12 15:46 UTC
Labels: type: question, priority: p2

**Comment by lmagyar89** [comment] 2025-07-19 07:48
I'm getting the same warn. Problem is that pubsub thread pools get precendence before default taskScheduler.
My proposal is the same: @AutoConfigureAfter(TaskSchedulingAutoConfiguration.class) to the GcpPubSubAutoConfiguration.
@meltsufin With your suggestion the problem is it is not considering TaskSchedulingProperties.
I think it is an easy fix to get rid of this warning, also scheduled task executor will be works as expected just like project use spring boot without spring gcp.

Please consider the proposed changed again.
