### ISSUE TITLE
Logs are displayed twice 

### ISSUE THREAD

**Issue by aelkerda** [GoogleCloudPlatform/spring-cloud-gcp#1387] opened 2022-12-14 10:22 UTC
My logs are duplicated twice
**They are displayed grouped together inside the parent request**
![image](https://user-images.githubusercontent.com/93186493/207557849-15180b10-308a-4e22-af45-cc7e5554d5df.png)

**and they are displayed each one alone:**
![image](https://user-images.githubusercontent.com/93186493/207557302-d779e4b0-3cb1-4c5e-a3d5-8a68f84fa9d6.png)

**Log back file:**
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="com/google/cloud/spring/logging/logback-appender.xml"/>
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>

    <springProfile name="dev | sandbox | prod">
        <root level="INFO">
            <appender-ref ref="STACKDRIVER"/>
        </root>
    </springProfile>
</configuration>

is this a normal behavior?, I just want to display logs once under the parent request

**Comment by JoeWang1127** [comment] 2022-12-14 18:56
Hi @aelkerda, could you post a sample so that I can start investigate from there.

**Comment by meltsufin** [comment] 2022-12-19 17:57
This could happen if you are also logging to stdout. If you are able to provide a reproducer, please reopen.

**Comment by aelkerda** [comment] 2022-12-21 11:27
Hello,

I'm using @SLF4j from lombok to log
I just added **spring.cloud.gcp.logging.enabled=true**

and the following logback-spring.xml file
![image](https://user-images.githubusercontent.com/93186493/208894714-097c3d98-fe4c-41ec-8d92-54b5e3032726.png)

**Comment by meltsufin** [comment] 2022-12-21 14:59
If both, `STACKDRIVER` and `CONSOLE` appenders are enabled, you will see duplicate log messages.

**Comment by aelkerda** [comment] 2022-12-21 15:42
Hello @meltsufin 
But I'm only using console in local and default environments
and the screenshot is from sandbox environment which has only stackdriver 
also the log concerning the service request (ex: /api/users/test) is displayed only once the problem is with the sub logs coming from this service request

**Comment by meltsufin** [comment] 2022-12-21 17:00
@aelkerda It might be just the way logs are displayed. What happens when you click on the little trace icon and choose to "Show all logs for this trace"?

**Comment by aelkerda** [comment] 2022-12-21 17:02
I shows the logs without duplication

**Comment by meltsufin** [comment] 2022-12-21 17:04
Thanks for the quick update! It seems to be a UI choice in Cloud Logging then. I'll close this issue.

**Closed by meltsufin** 2022-12-21 17:04 UTC
Labels: type: question, awaiting, priority: p3
