### ISSUE TITLE
Inconsistent Message Ordering with High-Frequency Publishing Interval

### ISSUE THREAD

**Issue by rastogirishabh** [GoogleCloudPlatform/spring-cloud-gcp#2008] opened 2023-07-07 05:30 UTC
## Issue
When publishing multiple events/message having the same ordering key on a interval of 1 to 500 ms, the message ordering is not maintained consistently.

Despite taking all the necessary steps to ensure proper ordering, (mentioned below) the consumed events are received out of order.

- publishing messages to a regional end-point.
- enabling message ordering flag at subscription level and
- enabling message ordering flag at the publisher level.

However, if a sleep delay of approximately 1 second is introduced before publishing the individual events, the messages are received in the expected order.

## Steps to reproduce
1. Set up a publisher-subscriber system with proper configuration for message ordering.
2. Publish a sequence of events with the same ordering key, each separated by a 1 to 500 ms interval. (Don't bring up the consumer yet)
3. Start the consumer that subscribes to a subscription which has message ordering flag enabled.
4. Observe the received order of the consumed events.

#### Configurations
```java
  @Bean
  public CredentialsProvider credentialsProvider() {
    return () ->
        ServiceAccountCredentials.fromStream(Files.newInputStream(Paths.get(credentialsFilePath)))
            .createScoped(PublisherStubSettings.getDefaultServiceScopes());
  }

  @Bean
  public PubSubPublisherTemplate pubSubPublisherTemplate(
      CredentialsProvider credentialsProvider, PubSubMessageConverter pubSubMessageConverter) {

    DefaultPublisherFactory factory = new DefaultPublisherFactory(() -> projectId);
    factory.setEnableMessageOrdering(true);
    factory.setCredentialsProvider(credentialsProvider);
    factory.setEndpoint("us-east1-pubsub.googleapis.com:443");

    PubSubPublisherTemplate template = new PubSubPublisherTemplate(factory);
    template.setMessageConverter(pubSubMessageConverter);
    return template;
  }

  @Bean
  public PubSubSubscriberTemplate subscriberTemplate(
      CredentialsProvider credentialsProvider, PubSubMessageConverter pubSubMessageConverter) {

    GcpPubSubProperties gcpPubSubProperties = new GcpPubSubProperties();
    gcpPubSubProperties.setKeepAliveIntervalMinutes(1);
    gcpPubSubProperties.initialize(projectId);

    DefaultSubscriberFactory factory =
        new DefaultSubscriberFactory(() -> projectId, gcpPubSubProperties);
    factory.setCredentialsProvider(credentialsProvider);

    PubSubSubscriberTemplate template = new PubSubSubscriberTemplate(factory);
    template.setMessageConverter(pubSubMessageConverter);
    return template;
  }

  @Bean
  public PubSubTemplate pubSubTemplateBean(
      PubSubPublisherTemplate pubSubPublisherTemplate,
      PubSubSubscriberTemplate subscriberTemplate) {
    return new PubSubTemplate(pubSubPublisherTemplate, subscriberTemplate);
  }
```
#### Publisher and Subscriber
```java
  private void publishWithOrdering(List<Item> items) {
    items.forEach(
        item -> {
          log.info(
              "Publishing item (with ordering key) : [{}] with event description : [{}] ",
              item.getItemNumber(),
              item.getItemDescription());

          pubSubTemplate.publish(
              topic(), item, Collections.singletonMap(GcpPubSubHeaders.ORDERING_KEY, "1234"));

          try {
            Thread.sleep(100);
          } catch (InterruptedException e) {
            throw new RuntimeException(e);
          }
        });
  }

@Configuration
public class PubSubListener {
  @Bean
  public Subscriber itemListener(PubSubTemplate pubSubTemplate) {

    return pubSubTemplate.subscribeAndConvert(getSubscription(), this::handleMessage, Item.class);
  }

  public void handleMessage(ConvertedBasicAcknowledgeablePubsubMessage<Item> message) {
    Item payload = message.getPayload();
    log.info(
        "Item received with item ID : [{}] and event description : [{}] with ordering key [{}]",
        payload.getItemNumber(),
        payload.getItemDescription(),
        message.getPubsubMessage().getOrderingKey());

    message.ack();
  }

  public String getSubscription() {
    return "item-topic-subscription";
  }
}
```

## Dependencies
```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>spring-cloud-gcp-dependencies</artifactId>
      <version>4.5.1</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
</dependency>

<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>spring-cloud-gcp-starter</artifactId>
</dependency>

```

**Comment by meltsufin** [comment] 2023-07-07 14:41
I don't see anything obviously wrong in your setup. Can you please file a Google Cloud Support ticket for further investigation?
Another thing you can try is to use pure Pub/Sub client library without Spring Cloud GCP, and see if you observe the same result.

**Comment by rastogirishabh** [comment] 2023-07-08 20:49
The Google Pub/Sub team has marked the issue as closed and suggested transferring it to the Spring Cloud GCP board. However, I will attempt to submit a support ticket to address the matter. 

Can you identify any possible bug in this scenario?

**Comment by meltsufin** [comment] 2023-07-10 14:23
I don't see anything obvious, but I think Cloud Support is the way to go for a more complete investigation.
If you want to debug on your own, I would try to use the Pub/Sub client library directly without Spring Cloud GCP.

**Comment by rastogirishabh** [comment] 2023-07-28 11:40
Google Pub/Sub guys are unable to find out any relevant issues on their Java based SDK. They are also suggesting to check it with Spring Pub/Sub team as it is specific to the Spring. 

How do you want to proceed further on this one? Are you guys planning to take it up and fix it in the upcoming releases?

**Comment by meltsufin** [comment] 2023-07-28 16:13
We need to diagnose the problem before we can fix it. If you have a reproducer we can run, that could help. Otherwise, were you able to file a ticket with Google Cloud Support?

**Comment by rastogirishabh** [comment] 2023-07-28 17:41
I raised a regular GitHub issue with Google Pub/Sub team. I don't have an enterprise account to raise support ticket with Google Cloud Support. 
And what kind of reproducer is required? Should I share a GitHub repo with the above code that has an issue?

**Comment by meltsufin** [comment] 2023-07-28 17:56
Yes, a GitHub repo with precise instructions on how to setup the environment, run the app, and see the problem. Ideally, you would have an integration test in the repo that would be failing.

**Comment by rastogirishabh** [comment] 2023-08-01 15:00
Here is the repo that can be used to replicate the issue. https://github.com/rastogirishabh/pubsub 
Readme file contains the precise instruction on how to build and run the app. Let me know if I can help any further.

**Comment by burkedavison** [comment] 2023-08-01 22:19
Thank you @rastogirishabh for the clear reproducer.

I've reproduced the issue with your project.

![image](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/40617934/5e116882-08aa-441f-b715-579d0615189b)

* [`PubSubPublisherTemplate.publish(topic, message)`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/publisher/PubSubPublisherTemplate.java#L93-L94) uses its `publisherFactory` to `createPublisher` for each invocation.
* [`DefaultPublisherFactory.createPublisher(topic)`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultPublisherFactory.java#L180-L186) always builds a new `Publisher`.
* [`Publisher.Builder`](https://github.com/googleapis/java-pubsub/blob/main/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java#L712-L715) uses an `InstantiatingExecutorProvider` by default.
* [`InstantiatingExecutorProvider`](https://github.com/googleapis/sdk-platform-java/blob/9793a313e785a321fa71e74b92e812bd9c6918e4/gax-java/gax/src/main/java/com/google/api/gax/core/InstantiatingExecutorProvider.java#L38-L41) constructs a new `ScheduledExecutorService` every time `getExecutor()` is called.

So it appears the PubSubPublisherTemplate is passing each message to a different executor, thus the onSuccess callbacks are out of order because the publishing events are too.

**Comment by meltsufin** [comment] 2023-08-02 02:33
By default, a `CachingPublisherFactory` is [auto-configured](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/95bcafbed3b9bb2e040386a9580b60945149e1e8/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java#L376).

As you pointed out, I think the issue is more with the asynchronous publishing. The `publish()` method returns a future, which you should wait for before proceeding with publishing the next message, and the reproducer doesn't wait.

**Comment by rastogirishabh** [comment] 2023-08-02 07:06
Sure! In a production scenario, we may want to publish messages asynchronously without waiting for the `publish()` method to return while still ensuring that the messages maintain their ordering. How can we achieve this?

**Comment by meltsufin** [comment] 2023-08-02 13:19
@maitrimangal Can you please validate our diagnosis here? Is it correct to assume that you can't do asynchronous publishing, even with the same `Publisher` if ordering is required.

**Comment by burkedavison** [comment] 2023-08-02 13:57
Verified this fixes the reproducer project. `PubSubConfig.pubSubPublisherTemplate()`:
```java
    DefaultPublisherFactory factory = new DefaultPublisherFactory(() -> projectId);
    // ... configure factory ...
    PubSubPublisherTemplate template = new PubSubPublisherTemplate(new CachingPublisherFactory(factory));
    // ...
```

@rastogirishabh : Closing this issue, but please reopen if needed.

**Closed by burkedavison** 2023-08-02 13:57 UTC
Labels: type: bug, pubsub

**Comment by rastogirishabh** [comment] 2023-08-02 15:00
Thanks @burkedavison for the resolution. I will test it and let you know if the issue persist. 
But I wanted to check, how were you able to print the entire payload in the logs as shown below? 

![pub-sub-github-issue](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/67154643/47b5d67a-99ad-4752-a3d5-d3b390573a78)

I am using 4.5.1 version and can't find the log statement having the `PubsubMessage` object itself in the [PubSubPublisherTemplate](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/95bcafbed3b9bb2e040386a9580b60945149e1e8/spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/publisher/PubSubPublisherTemplate.java#L113).
