### ISSUE TITLE
pull a latest message only

### ISSUE THREAD

**Issue by waytoharish** [GoogleCloudPlatform/spring-cloud-gcp#1207] opened 2022-08-02 03:07 UTC
Hi Team,
I am working on one of the solution where I need to pull the latest message from the topic but I am not able to find a way for the same. Is there any way to do the same?
I am using -
`pubSubTemplate.pullAndConvert("topic-sub", 1, Boolean.TRUE, String.class)` 

to pull the message . Whenever there is a new message it also return the old message to.

Any advice or that is not supported feature in GCP using Spring

**Comment by zhumin8** [comment] 2022-08-02 13:44
It sounds like you did not acknowledge so the older messages gets redelivered repeatedly.
Look for the code snippet [in our documentation here](https://googlecloudplatform.github.io/spring-cloud-gcp/3.3.0/reference/html/index.html#example) for an example of acknowledging with the `pubSubTemplate.subscribe()`. 
And this [link](https://cloud.google.com/pubsub/docs/subscriber#subscription-workflow) to Pub/Sub documentation on acknowledging in subscription.

**Comment by waytoharish** [comment] 2022-08-03 04:27
I did acknowledge the message but still I can see multiple messages pulled which was already ack

 var message=pubSubTemplate.pull(TOPIC_NAME, 1, Boolean.TRUE);
        pubSubTemplate.ack(message);
        message.forEach(msg -> {
                System.out.println("Message ID is >>>>>>>>>"+msg.getPubsubMessage().getAttributesMap().get("messageId"));
         
        });
message length sometime greater than >1.

Am I doing something wrong

**Comment by zhumin8** [comment] 2022-08-03 15:21
One possibility is that the acknowledge did not success, you can capture that by a try-catch block like the one in the sample code [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/e04f755f75c98619c11fde42106cff81e95f1540/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-sample/src/main/java/com/example/WebController.java#L93-L101). 
The other thing I noticed is that you already set `maxMessages` in the `pubSubTemplate.pull()` to be 1. Are you getting more than one message in one single call? If so, can you provide a simple reproducer repo to show the issue?

**Comment by elefeint** [comment] 2022-09-08 15:21
@2021H1030039G This is very unlikely to be an actual issue in Spring Cloud GCP

@waytoharish The behavior you are seeing could be due to a couple of reasons:
1) a large backlogs of small messages that take a while to process ([this documentation](https://cloud.google.com/pubsub/docs/pull#streamingpull_dealing_with_large_backlogs_of_small_messages) is for streaming pull, but if you are pulling more message than can be processed, the synchronous pull could lead to the same behavior)
2) Enabling exactly-once delivery, which will lead to all messages after an undelivered one getting redelivered.

Look closely at the acknowledgement deadline on your subscription to understand redelivery patterns for this application.

**Comment by elefeint** [comment] 2022-10-20 14:16
Closing; please reopen if you are still having issues.

**Closed by elefeint** 2022-10-20 14:16 UTC
Labels: question, pubsub, P3
