### ISSUE TITLE
Zipkin not usable when using any of the GCP starters

### ISSUE THREAD

**Issue by Milzor** [GoogleCloudPlatform/spring-cloud-gcp#1693] opened 2023-04-04 08:59 UTC
**Describe the bug**
#1630 introduced a bug when NOT using gcp trace.

I want to use zipkin instead of cloud trace and not able to correctly configure my application as ZipkinAutoConfiguration is skipped. I do want to use PubSub for sending messages.

**Sample**
```
         ...
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>io.zipkin.brave</groupId>
            <artifactId>brave-instrumentation-messaging</artifactId>
        </dependency>
        <dependency>
            <groupId>io.zipkin.reporter2</groupId>
            <artifactId>zipkin-reporter-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>spring-cloud-gcp-pubsub-stream-binder</artifactId>
        </dependency>
        ...
```

**Comment by suztomo** [comment] 2023-04-04 14:49
Memo: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1630 was fixed by https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1637

**Comment by JoeWang1127** [comment] 2023-04-04 14:51
Hi @Milzor, could you provide a minimum reproducer so that I can debug the issue?

**Comment by dimi-nk** [comment] 2023-04-11 18:03
We have the same issue. We use some other GCP products, but we don't use GCP tracing. I think it makes sense that both the auto-configuration and the filter get disabled via the enable prop. I pushed a PR for your consideration.

**Comment by wilkinsona** [comment] 2023-04-12 14:26
Thanks for bringing this issue to my attention, @dimi-nk.

@JoeWang1127 I'm one of the Spring Boot maintainers and I'd like to understand a bit more about why you need to exclude `ZipkinAutoConfiguration`. Exclusion should always be a last resort. Ideally, it should be possible to have things back off by defining your own beans instead. If that doesn't work at the moment for this projects needs, it may be that we can make some changes in Boot to improve the situation.

**Comment by JoeWang1127** [comment] 2023-04-12 14:46
@wilkinsona thanks for you attention.

The reason we exclude `ZipkinAutoConfiguration` is that it brings incompatible `AsyncReporter`, see #1630. 

If excluding `ZipkinAutoConfiguration` is not appropriate, what is the recommended way to fix this issue?

**Comment by wilkinsona** [comment] 2023-04-12 16:46
I don't yet I have enough context to answer that, unfortunately.

I wonder if there's any of `ZipkinAutoConfiguration` that is useful in the context of GCP. You are losing a number of other beans by disabling it completely which feels quite drastic. Perhaps we need a mechanism to only parts of the auto-configuration while keeping the rest of it.

In terms of what's possible at the moment, Boot's `AsyncReporter` will back off if there's an `AsyncReporter` already defined. Could you define one of your own that is compatible or that does nothing?

**Comment by dimi-nk** [comment] 2023-04-12 17:05
@wilkinsona, maybe it's also worth discussing workarounds that could help others. I could not find a way to disable the `TraceAutoConfigurationFilter` bean. I tried various `@ComponentScan` approaches like the following, but the bean keeps getting included (maybe it's done through a different mechanism?).

```java
@ComponentScan(
    basePackageClasses = TraceAutoConfigurationFilter.class,
    excludeFilters = @Filter(type = REGEX, pattern = "\\.TraceAutoConfigurationFilter$"))
```

After hours of trying, the only thing that worked for me was to re-import the auto-configuration in our configuration class, e.g.

```java
@Configuration(proxyBeanMethods = false)
@Import(ZipkinAutoConfiguration.class)
public class TracingConfiguration { }
```

This could be a good enough workaround for the time being. Please do share if you know of a better way to tackle this.

**Comment by JoeWang1127** [comment] 2023-04-12 17:19
> In terms of what's possible at the moment, Boot's `AsyncReporter` will back off if there's an `AsyncReporter` already defined. Could you define one of your own that is compatible or that does nothing?

We do have a `AsyncReporter` Bean defined in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/deb4239696360dadfe8ecfcda692adf344938909/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/trace/StackdriverTraceAutoConfiguration.java#L171

**Comment by wilkinsona** [comment] 2023-04-12 17:27
There are a couple of reasons why that may not have caused the `AsyncReporter` from `ZipkinAutoConfiguration` to back off:

1. Your `@Bean` method is typed as a `Reporter`. At the moment, the `AsyncReporter` in Boot will only back off in the presence of another `AsyncReporter`. We should possible change that so it will back off in the presence of any `Reporter`. However, generally speaking, the return type in the signature of `@Bean` methods should be as specific as possible so it's worth changing it to return. `AsyncReporter<Span>` even if it doesn't help with this particular problem.
2. `StackdriverTraceAutoConfiguration` has been processed after `ZipkinAutoConfiguration`. This can be addressed by adding `ZipkinAutoConfiguration` to the existing `@AutoConfigureBefore` annotation.

**Comment by JoeWang1127** [comment] 2023-04-12 19:47
@wilkinsona, thanks for your comments.

I intend to go with your 1st suggestion. Will bring the PR to the team for review.

**Closed** 2023-04-14 14:23 UTC
Labels: type: bug, priority: p2

**Comment by dimi-nk** [comment] 2023-04-14 14:26
Thanks @JoeWang1127  and @wilkinsona
