### ISSUE TITLE
No environment placeholder in configuration properties

### ISSUE THREAD

**Issue by ElectroLutz** [GoogleCloudPlatform/spring-cloud-gcp#491] opened 2021-06-07 08:21 UTC
Hey,

I guess that after #131 (edit: I guess it's since 2.0.2) it's not possible to have a configuration like the following anymore:
```
spring.cloud.gcp:
  sql:
    enabled: ${CLOUD_SQL_ENABLED:false}
    database-name: ${CLOUD_SQL_DATABASE:}
    instance-connection-name: ${CLOUD_SQL_INSTANCE:}
    credentials:
      encoded-key: ${CLOUD_SQL_KEY:}
```
The placeholders are not replaced anymore and the values are passed as they are in the application.yml.

How can I archive that they are replaced again? I don't want to use any config management, because until now the environment variables been doing their job.

Cheers
Marko

**Comment by meltsufin** [comment] 2021-06-08 00:52
I think this is more likely caused by #273.
We disabled resolving placeholders to avoid issues with Secrets Manager placeholders resolver, but maybe we should just register a smarter resolver, or create an option to enable placeholder resolution.
cc/ @dzou.

**Closed** 2021-06-08 19:11 UTC
Labels: P3, question, team-starter-bug

**Comment by ElectroLutz** [comment] 2021-06-08 20:33
Thank you for the fast fix! Didn’t expect that.
