### ISSUE TITLE
Unable to query using FirestoreReactiveRepository

### ISSUE THREAD

**Issue by arturomelo-kareo** [GoogleCloudPlatform/spring-cloud-gcp#2330] opened 2023-11-07 20:19 UTC
**Describe the bug**
Unable to query by Guid (String) and name (String)

Tested on version 3.7.0 and above 
This feature works fine on version 3.5.3

**Sample**

The following API definition fails on a FirestoreReactiveRepository

Mono<UserSettingsEntity> findByUserGuidAndName(String userGuid, String name);

Exception

```
[firestore] WARNING: Operation failed: Document parent name "projects/demo-example/databases/(default)/documents/documents" lacks "/" at index 61.
[firestore] com.google.cloud.datastore.core.exception.InvalidConversionException: Document parent name "projects/demo-example/databases/(default)/documents/documents" lacks "/" at index 61.
[firestore] 	at com.google.cloud.datastore.core.exception.InvalidConversionException.checkConversion(InvalidConversionException.java:44)
[firestore] 	at com.google.cloud.datastore.core.firestorev1.converter.FirestoreV1ResourceNameParser.parseSlashAllowTrailing(FirestoreV1ResourceNameParser.java:132)
[firestore] 	at com.google.cloud.datastore.core.firestorev1.converter.FirestoreV1ResourceNameParser.parseSlash(FirestoreV1ResourceNameParser.java:127)
[firestore] 	at com.google.cloud.datastore.core.firestorev1.converter.FirestoreV1ResourceRefToRepConverter.parseEntityCollectionIdResourceIdPairs(FirestoreV1ResourceRefToRepConverter.java:297)
[firestore] 	at com.google.cloud.datastore.core.firestorev1.converter.FirestoreV1ResourceRefToRepConverter.convertEntityParentRefAllowFirestoreRelative(FirestoreV1ResourceRefToRepConverter.java:89)
[firestore] 	at com.google.cloud.datastore.core.firestorev1.converter.FirestoreV1RequestToRepConverter.parseParent(FirestoreV1RequestToRepConverter.java:620)
[firestore] 	at com.google.cloud.datastore.emulator.impl.util.FirestoreEmulatorConverters.parseParent(FirestoreEmulatorConverters.java:520)
[firestore] 	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1Router.inferDatabaseRef(CloudFirestoreV1Router.java:481)
[firestore] 	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1Router.runQuery(CloudFirestoreV1Router.java:178)
[firestore] 	at com.google.cloud.datastore.emulator.firestore.v1.FirestoreV1GrpcAdapter$1.lambda$runQuery$10(FirestoreV1GrpcAdapter.java:176)
[firestore] 	at com.google.cloud.datastore.emulator.firestore.v1.FirestoreV1GrpcAdapter.streaming(FirestoreV1GrpcAdapter.java:80)
[firestore] 	at com.google.cloud.datastore.emulator.firestore.v1.FirestoreV1GrpcAdapter$1.runQuery(FirestoreV1GrpcAdapter.java:176)
[firestore] 	at com.google.firestore.v1.FirestoreGrpc$MethodHandlers.invoke(FirestoreGrpc.java:1187)
[firestore] 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
[firestore] 	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
[firestore] 	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
[firestore] 	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
[firestore] 	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
[firestore] 	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
[firestore] 	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
[firestore] 	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
[firestore] 	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
[firestore] 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:346)
[firestore] 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
[firestore] 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[firestore] 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
[firestore] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[firestore] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[firestore] 	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by arturomelo-kareo** [comment] 2023-11-08 00:57
Ok, it seems that this issue only happens when using the emulator. The class GcpFirestoreEmulatorAutoConfiguration duplicates the /document element in the path

`return new FirestoreTemplate(
          firestoreStub, rootPath + "/documents", classMapper, firestoreMappingContext);`

**Comment by meltsufin** [comment] 2023-11-13 20:18
Seems like a duplicate of https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/2290.

**Closed** 2023-11-14 17:13 UTC
Labels: type: bug, priority: p3
