### ISSUE TITLE
 CI `Generator - Showcase Tests / showcaseTests` failure

### ISSUE THREAD

**Issue by lqiu96** [GoogleCloudPlatform/spring-cloud-gcp#2564] opened 2024-01-29 22:16 UTC
Seeing error:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22.800 s
[INFO] Finished at: 2024-01-25T00:25:58Z
[INFO] ------------------------------------------------------------------------
fixed /home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-generator/sdk-platform-java/WORKSPACE
fixed /home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-generator/sdk-platform-java/WORKSPACE
fixed /home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-generator/sdk-platform-java/WORKSPACE
/home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-generator/sdk-platform-java/showcase/BUILD.bazel/BUILD: file not found or not readable
Error: Process completed with exit code 2.
```

in the `Verify generation of showcase-spring-starter` step.

Example PR: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2542

**Comment by zhumin8** [comment] 2024-02-05 20:09
duplicate of #2214

**Closed by zhumin8** 2024-02-05 20:09 UTC
Labels: type: bug, priority: p2
