### ISSUE TITLE
Reactive firestore repositories cause bean dependency cycle when used in a MeterBinder

### ISSUE THREAD

**Issue by JakobFels** [GoogleCloudPlatform/spring-cloud-gcp#1113] opened 2022-05-09 09:39 UTC
Spring Boot version: 2.6.7
Spring cloud gcp version (BOM): 3.2.1

We seem to be running into an issue similar to https://github.com/spring-projects/spring-boot/issues/27591.
We recently migrated one of our metric sources to use a spring data repository. This seems to cause a bean dependency cycle caused by `startupTimeMetrics` (See attached bean cycle screenshot).
![image](https://user-images.githubusercontent.com/4647840/167384649-19f3744f-a746-43cd-b168-ea05b4fd12bc.png)

Looks to me like Firestore repositories cause the metrics stack to be initialized, which then causes a cycle if the repository is used in a Meterbinder.

A project to reproduce the issue is located at https://github.com/JakobFels/FirestoreMetricsReproducer

**Comment by JakobFels** [comment] 2022-05-09 15:17
Hi,

The issue does not occur in a 'plain' spring data application, using spring data jpa for example (see https://github.com/spring-projects/spring-boot/issues/30902)
The cycle is only present if a firestore repository is used.

**Comment by elefeint** [comment] 2022-06-24 14:23
@JakobFels Thank you, the reproducer was very helpful. I've looked into it some more, and the issue is indeed not Firestore-specific.  As a workaround, avoid implementing `MeterBinder` -- adding gauges per [Spring Boot docs](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.metrics.registering-custom) will allow you to register the metrics after both the service and the registry have already been instantiated (at that point, it probably does not make sense to call this a Binder).

```
@Component
public class ReproducerMeterBinder {

    private final MeterService meterService;

    public ReproducerMeterBinder(MeterRegistry registry, MeterService meterService) {
        this.meterService = meterService;
        Gauge.builder("test", meterService::count)
                .register(registry);
    }
}
```

The root issue was as follows: `org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport` brings in `org.springframework.data.repository.core.support.EventPublishingRepositoryProxyPostProcessor`. Spring Data publishes `org.springframework.data.mapping.context.MappingContextEvent` when entity type is registered in  `RepositoryFactoryBeanSupport.afterPropertiesSet()`. Because `startupTimeMetrics` is registered as an `ApplicationListener`, it has to get instantiated at that point, causing the cycle.

**Comment by zhumin8** [comment] 2022-08-08 20:26
Closing as part of cleanup. Please re-open if it's still relevant.

**Closed by zhumin8** 2022-08-08 20:26 UTC
Labels: question, P3, firestore

**Comment by wilkinsona** [comment] 2022-08-09 08:48
This is still relevant. IMO, it should be re-opened.

**Comment by elefeint** [comment] 2022-08-09 13:23
The cycle was introduced in the user's code -- injecting MeterRegistry per Spring Boot documentation would avoid it.
There is nothing Firestore specific about this:

> The root issue was as follows: `org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport` brings in `org.springframework.data.repository.core.support.EventPublishingRepositoryProxyPostProcessor`. Spring Data publishes `org.springframework.data.mapping.context.MappingContextEvent` when entity type is registered in  `RepositoryFactoryBeanSupport.afterPropertiesSet()`. Because `startupTimeMetrics` is registered as an `ApplicationListener`, it has to get instantiated at that point, causing the cycle.

**Comment by wilkinsona** [comment] 2022-08-09 13:32
Sorry. I guess I misunderstood [this comment](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1113?notification_referrer_id=NT_kwDOAA30-rEzNTg1NDM3MjY0OjkxNDY4Mg#issuecomment-1121238310) from @JakobFels.

**Comment by JakobFels** [comment] 2022-08-09 13:45
The documentation also specifies that implementing the MeterBinder interface should also work.

**Comment by elefeint** [comment] 2022-08-09 14:00
Right; because spring-data-jpa does not implement `RepositoryFactoryBeanSupport`. But spring-data-r2dbc does, so it makes for a good reproducer.

https://github.com/elefeint/FirestoreMetricsReproducer/tree/h2-reproducer shows the same issue with H2 R2DBC driver.

While implementing `MeterBinder` works in principle, when combined with `RepositoryFactoryBeanSupport`, and likely other event-publishing infrastructure, the end-user application ends up creating a cycle.

**Comment by wilkinsona** [comment] 2022-08-09 14:36
Thanks, @elefeint. I've re-opened the Spring Boot issue.
