### ISSUE TITLE
Firestore `findByIdAndArrayContains` / `existsByIdAndArrayContains` doesn't work

### ISSUE THREAD

**Issue by jenswet-el** [GoogleCloudPlatform/spring-cloud-gcp#424] opened 2021-03-31 15:49 UTC
Hi!

I'd like to use GCP Firestore integration. Most things seem to work, except some specific queries:

Methods doing `findById` / `existsById` combined by AND with a contains on a list do not work.

**Sample**
```java
@Document(collectionName = "examples")
public class Example {
    @DocumentId
    private String id;
    private List<String> array;
}
```
```java
public interface ExampleRepository extends FirestoreReactiveRepository<Example> {
   
    Mono<Boolean> existsByIdAndArrayContains(String id, String someString); // does not work
    Mono<Boolean> existsByIdAndArrayContaining(String id, String someString); // does not work
    Mono<Boolean> existsByIdAndArrayIsContaining(String id, String someString); // does not work
    Mono<Boolean> existsByArrayContains(String someString); // works
    Mono<Boolean> existsById(String id); // works

    Mono<Example> findByIdAndArrayContains(String id, String someString); // does not work
    Mono<Example> findByIdAndArrayContaining(String id, String someString); // does not work
    Mono<Example> findByIdAndArrayIsContaining(String id, String someString); // does not work
    Mono<Example> findByArrayContains(String someString); // works
    Mono<Example> findById(String id); // works
```

`byId` and `ArrayContains` work alone but not together.

Did I miss something or is that a bug?

Thanks!

**Comment by meltsufin** [comment] 2021-03-31 18:30
What's the error that you're getting? I think it's a limitation in Firestore. Also, what's your usecase for searching by ID and some other attribute? ID already narrows it down to a single entity.

**Comment by jenswet-el** [comment] 2021-04-01 07:54
There is no error, but the result is always null / empty. According to the docs I thought it should be possible to combine findBy with Contains.

There is no real usecase of find but of exists. It would allow to check for example whether an event object contains a userId in a (big) guests array without copying the whole object from the database. I know this would be not the best database design, but this problem came across in a quick and dirty prototype.

**Comment by meltsufin** [comment] 2021-04-02 03:19
I think the problem is that ID is technically not a field of the document. Under the hood, we use `StructuredQuery` with `FieldFilter`. So, if there is a way to construct such a query, then we can potentially accommodate this usecase.

We had a similar issue in Spring Data Datastore (https://github.com/spring-cloud/spring-cloud-gcp/issues/1720) and it was resolved in https://github.com/spring-cloud/spring-cloud-gcp/pull/1748. It might be possible to do the same kind of fix for Firestore, but I'm not sure the Firestore API allows for it.

**Closed** 2021-06-24 21:24 UTC
Labels: P3, firestore, team-starter-bug
