### ISSUE TITLE
java.lang.ClassNotFoundException: com.google.cloud.sql.ConnectorRegistry when using spring-cloud-gcp v.5.1.0

### ISSUE THREAD

**Issue by amynguyen780** [GoogleCloudPlatform/spring-cloud-gcp#2709] opened 2024-03-18 15:43 UTC
**Describe the bug**
I bumped to the latest version of spring-cloud-gcp (5.1.0) for the various dependencies that use:
```
<dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>spring-cloud-gcp-pubsub</artifactId>
      <version>${spring-cloud-gcp.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>spring-cloud-gcp-core</artifactId>
      <version>${spring-cloud-gcp.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>spring-cloud-gcp-starter-sql-postgresql</artifactId>
      <version>${spring-cloud-gcp.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
      <version>${spring-cloud-gcp.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>spring-cloud-gcp-starter</artifactId>
      <version>${spring-cloud-gcp.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>spring-cloud-gcp-autoconfigure</artifactId>
      <version>${spring-cloud-gcp.version}</version>
    </dependency>
```
And now I get the error `java.lang.ClassNotFoundException: com.google.cloud.sql.ConnectorRegistry` when I try to start my application. 
The stacktrace:
```
Caused by: java.lang.NoClassDefFoundError: com/google/cloud/sql/ConnectorRegistry
	at com.google.cloud.spring.autoconfigure.sql.CloudSqlEnvironmentPostProcessor.postProcessEnvironment(CloudSqlEnvironmentPostProcessor.java:86)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:109)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:94)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:329)
```

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by meltsufin** [comment] 2024-03-18 16:07
@ttosta-google FYI

**Comment by ttosta-google** [comment] 2024-03-18 16:15
I will investigate this issue.

**Comment by ttosta-google** [comment] 2024-03-26 20:02
Thanks @amynguyen780 for reporting this issue.

Try adding the BOM to your pom.xml like recommended [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp?tab=readme-ov-file#spring-framework-on-google-cloud-bill-of-materials-bom).

```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>spring-cloud-gcp-dependencies</artifactId>
            <version>5.1.0</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

Please let us know if it fixes this issue.

**Comment by amynguyen780** [comment] 2024-03-27 15:37
So I added what you suggested and removed all the other dependencies I specified in the issue description since I assumed that this pom would cover all of those but then it apparently didn't and I needed to add back `spring-cloud-gcp-pubsub` and `spring-cloud-gcp-starter-sql-postgresql`, and then I get the same error when I start the application about `java.lang.NoClassDefFoundError: com/google/cloud/sql/ConnectorRegistry`.

**Comment by amynguyen780** [comment] 2024-03-28 18:46
@ttosta-google any ideas?

**Comment by ttosta-google** [comment] 2024-03-28 20:53
@amynguyen780 The `<dependencyManagement>` only controls the version, it does not add the dependency.

My pom.xml file is:

```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>spring-cloud-gcp-dependencies</artifactId>
            <version>5.1.0</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>spring-cloud-gcp-starter-sql-postgresql</artifactId>
     </dependency>
</dependencies>
```

Please try the following:

```
mvn clean install -U

mvn spring-boot:run
```

I was not able to reproduce your issue. 

The latest changes are used by the [spring-cloud-gcp-sql-postgres-sample](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-sample) and it works.

**Comment by amynguyen780** [comment] 2024-04-01 14:47
Got it. Ok so then I tried leaving all of the dependencies I had specified before but removed the pinned version at those individual dependencies and used the dependencyManagement pom import to specify the version, but I'm still getting the same error when trying to run the application. Did `com.google.cloud.sql.ConnectorRegistry` get moved to a different library in the version bump?

**Comment by amynguyen780** [comment] 2024-04-01 15:25
Ah I see this particular file got changed [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2643/files#diff-8adf0e3e40be11f2f9fc27a0c9ca654f0af8ea7dc2d41feaa82408be70d4ad9c). And I ran `mvn dependency:tree` and saw:
```
[INFO] +- com.google.cloud:spring-cloud-gcp-starter-sql-postgresql:jar:5.1.0:compile
[INFO] |  +- com.google.cloud.sql:postgres-socket-factory:jar:1.11.1:compile
[INFO] |  |  \- com.google.cloud.sql:jdbc-socket-factory-core:jar:1.11.1:compile
```
So weirdly, I'm not pulling in the version specified in the pom.xml here but an older one...

**Comment by ttosta-google** [comment] 2024-04-02 14:20
The version of `com.google.cloud.sql:postgres-socket-factory` is defined in the `<dependencyManagement>` section [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/71bb4a51ebaf71442bdfbfb2e351f6883f89a779/spring-cloud-gcp-dependencies/pom.xml#L256). It is possible that another library imported by your project is setting the version to `1.11.1`. To confirm this, please run  again and check if the library is being used in multiple places.

To force the version `1.16.0`  you could add the following to your `<dependencyManagement>`:

```
<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.google.cloud</groupId>
				<artifactId>spring-cloud-gcp-dependencies</artifactId>
				<version>5.1.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.google.cloud.sql</groupId>
				<artifactId>postgres-socket-factory</artifactId>
				<version>1.16.0</version>
			</dependency>
			<dependency>
				<groupId>com.google.cloud.sql</groupId>
				<artifactId>jdbc-socket-factory-core</artifactId>
				<version>1.16.0</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

It is only recommended if your project has two libraries defining the version for `com.google.cloud.sql:postgres-socket-factory`. If your projects only needs `spring-cloud-gcp-starter-sql-postgresql`, them adding the POM `com.google.cloud:spring-cloud-gcp-dependencies` should be enough.

**Comment by amynguyen780** [comment] 2024-04-02 16:05
Looking at the maven dependency tree, I see that I'm only pulling the `postgres-socket-factory` and `jdbc-socket-factory-core` dependencies from `spring-cloud-gcp-starter-sql-postgresql` which is at v5.1.0. I then specified these two dependencies explicitly with v1.16.0 pinned as you have above and it's now using those versions, but now I get another issue:
```
Caused by: java.lang.NoSuchMethodError: 'java.lang.String com.google.api.services.sqladmin.model.ConnectSettings.getDnsName()'
	at com.google.cloud.sql.core.DefaultConnectionInfoRepository.fetchMetadata(DefaultConnectionInfoRepository.java:217)
	at com.google.cloud.sql.core.DefaultConnectionInfoRepository.lambda$getConnectionInfo$0(DefaultConnectionInfoRepository.java:111)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
```

**Comment by ttosta-google** [comment] 2024-04-02 20:04
Please run `mvn help:effective-pom -Dverbose` and send me the output for `postgres-socket-factory` and `jdbc-socket-factory-core` dependencies.

My output is:

```
<dependency>
    <groupId>com.google.cloud.sql</groupId>  <!-- com.google.cloud:spring-cloud-gcp-dependencies:5.1.0, line 257 -->
    <artifactId>postgres-socket-factory</artifactId>  <!-- com.google.cloud:spring-cloud-gcp-dependencies:5.1.0, line 258 -->
    <version>1.16.0</version>  <!-- com.google.cloud:spring-cloud-gcp-dependencies:5.1.0, line 259 -->
</dependency>
``` 

Thanks!

**Comment by ttosta-google** [comment] 2024-04-03 15:56
Please remove the Cloud SQL dependencies from your project's `<dependencyManagement>` first. I would like to see which dependency is setting their version to `1.11.1`. Thanks!

**Comment by amynguyen780** [comment] 2024-04-03 16:27
Ah ok so I removed the pinned 1.16.0 version on these two dependencies and this is what I get:
```
<dependency>
        <groupId>com.google.cloud.sql</groupId>  <!-- com.spotify:ads-api-server:0.0.1-SNAPSHOT, line 310 -->
        <artifactId>postgres-socket-factory</artifactId>  <!-- com.spotify:ads-api-server:0.0.1-SNAPSHOT, line 311 -->
        <version>1.11.1</version>  <!-- com.spotify:bom:2279, line 1117 -->
        <scope>compile</scope>
      </dependency>
```

```
<dependency>
        <groupId>com.google.cloud.sql</groupId>  <!-- com.spotify:ads-api-server:0.0.1-SNAPSHOT, line 314 -->
        <artifactId>jdbc-socket-factory-core</artifactId>  <!-- com.spotify:ads-api-server:0.0.1-SNAPSHOT, line 315 -->
        <version>1.11.1</version>  <!-- com.spotify:bom:2279, line 1102 -->
        <scope>compile</scope>
      </dependency>
```

**Comment by ttosta-google** [comment] 2024-04-03 16:31
Now we can see that the Cloud SQL dependencies version is defined by `com.spotify:bom:2279`. Can you update it to `1.16.0` or `1.17.1` (latest) ?

**Comment by amynguyen780** [comment] 2024-04-03 17:06
Hm yeah I can look into that but it's strange that just specifying the version in my own project pom.xml wouldn't have been enough since usually that would override the older version being pulled in transitively

**Comment by ttosta-google** [comment] 2024-04-03 17:27
One option is to add the following to `com.spotify:bom` dependency, so the Cloud SQL deps version will be defined by `spring-cloud-gcp-dependencies:5.1.0`.

```
<exclusions>
    <exclusion>
        <groupId>com.google.cloud.sql</groupId>
        <artifactId>postgres-socket-factory</artifactId>
    </exclusion>
    <exclusion>
        <groupId>com.google.cloud.sql</groupId>
        <artifactId>jdbc-socket-factory-core</artifactId>
    </exclusion>
</exclusions>
``` 

Since this is not a bug, I'll close this ticket. If you encounter any new issues, feel free to report them by opening a new bug ticket. Thanks!

**Comment by ttosta-google** [comment] 2024-04-03 17:28
@meltsufin can you please close this issue? Thanks!

**Closed** 2024-04-04 15:39 UTC
Labels: type: bug, priority: p2, cloud-sql
